// Packages
import React from 'react'
import { Container, Header } from 'semantic-ui-react'

// Ours
import { host } from '../config/client'
import fetch from '../lib/fetch'

// Components
import Page from '../layout/Page'
import IssueForm from '../components/IssueForm'
import Error from '../components/Error'

class FormPage extends React.Component {
	constructor() {
		super()
		this.state = { success: false, failure: false, issue_url: '' }
	}

	static async getInitialProps({ req }) {
		// Get user profile
		let res = await fetch(req, '/api/userinfo')
		let profile
		if (res.ok) {
			profile = await res.json()
		}

		// Extract owner and name
		const match = /to\/([^\/]+)\/([^\/\?]+)/.exec(req.url)
		const owner = match[1]
		const name = match[2]

		const full_name = `${owner}/${name}`

		// Request submit.yml file
		res = await fetch(req, `/api/${full_name}/submit.json`)

		if (!res.ok) {
			return { found: false, full_name, profile }
		}

		try {
			const src = await res.json()
			return { found: true, src, full_name, profile }
		} catch (err) {
			return { found: false, full_name, profile }
		}
	}

	onSubmit(title, fields) {
		const body = fields
			.concat([
				`
---

This issue was generated by [submitter 🚀][repo]. Please report issues [here][issues]. Happy coding!

[repo]: https://github.com/ahmed-taj/submitter
[issues]: https://github.com/ahmed-taj/submitter/issues				
`
			])
			.join('\n\n')

		fetch(null, `/api/${this.props.full_name}/submit`, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({ title, body })
		})
			.then(res => {
				if (res.ok) {
					this.setState({ success: true })
					res.json().then(data => {
						this.setState({ issue_url: data['html_url'] })
					})
				}
			})
			.catch(err => {
				this.setState({ failure: true })
			})
	}

	wrapPage(component) {
		return <Page profile={this.props.profile}>{component}</Page>
	}

	render() {
		if (this.props.found && !this.state.success && !this.state.failure) {
			return this.wrapPage(
				<IssueForm
					meta={this.props.src.meta}
					fields={this.props.src.form}
					path={this.props.full_name}
					onSubmit={this.onSubmit.bind(this)}
				/>
			)
		} else if (this.state.success) {
			return this.wrapPage(
				<Container className="prefectly-centered">
					<Header as="h1">
						Nice!
						<Header.Subheader>
							A new issue has been opened at{' '}
							<a href={this.state.issue_url} style={{ color: 'purple' }}>
								{this.props.full_name}
							</a>
						</Header.Subheader>
					</Header>
				</Container>
			)
		} else if (this.state.failure) {
			return this.wrapPage(
				<Error>
					An unexpected error has occurred. You may want to check GitHub to make
					sure a new issue isn't actually been created
				</Error>
			)
		} else {
			const url = `https://github.com/${this.props.full_name}`
			return this.wrapPage(
				<Error>
					Looks like the repository at{' '}
					<a href={url} style={{ color: 'purple' }}>
						{this.props.full_name}
					</a>{' '}
					isn't submission friendly!
				</Error>
			)
		}
	}
}

export default FormPage
